# Generated by Django 6.0.6 on 2026-07-02 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.IntegerField()),
                ('verdict', models.CharField(max_length=20)),
                ('breakdown', models.JSONField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('female_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='female_matches', to='kundli.birthprofile')),
                ('male_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='male_matches', to='kundli.birthprofile')),
            ],
            options={
                'unique_together': {('male_profile', 'female_profile')},
            },
        ),
    ]
